### ISSUE TITLE
Buttons in the Control Theory - Supplemental - Vertical Arm Article reset voltage selection

### ISSUE THREAD

**Issue by benjamin-antupit** [gerth2/gerth2.github.io#2]
First of all, I love the series on PID tuning! I was just playing around with the [Vertical Arm article](https://trickingrockstothink.com/blog_posts/2019/10/26/controls_supp_arm.html) and noticed that when I move the voltage slider to any value greater than 0 and press one of the PID tuning buttons, the voltage shown in the sidebar graph resets to zero. Wiggling the voltage slider updates the sidebar to the expected output.
Please let me know if you want more details.

**Comment by gerth2** [comment]
Sweet, you're fast at reading it! 

What you're seeing is (I think) intentional. The voltage slider controls an "open-loop" methodology for control - it just applies a single voltage to the system. Any of the setpoint or PID controls flip the system to a closed loop control strategy. The text under the animation should be changing to indicate which mode the simulation is operating in.

Let me know if this isn't what you're seeing on your end.

Assuming this aligns with what you're seeing - any thoughts or recommendations on how to swap between the two? I'd considered an explicit switch, splitting the post into two sections, or maybe switching based on scroll distance..... none seemed super appealing, but this was all in my head. Let me know your thoughts!!

**Comment by benjamin-antupit** [comment]
Thanks! I set up an rss feed notification because I don't want to miss any of them.
I understand your explanation, but it's not what I'm seeing. Below is a quick screen recording. Please let me know if this is the expected behavior.
![screen-recording](https://user-images.githubusercontent.com/15172054/67627773-92a90f00-f817-11e9-94f9-b99858a2c87e.gif)

**Comment by gerth2** [comment]
Above and beyond in showing how to reproduce, thanks!! 

That's the behavior I have with one exception - the display to indicate "open loop" or "closed loop" isn't immediately visible (that's what I get for developing on giant monitors :P) 

Let me add an extra indicator to the top (above the charts) to indicate the mode. Hopefully it will be a bit more obvious when it switches back and forth.

**Comment by gerth2** [comment]
Ok, new version out. Overall behavior hasn't been changed, though there's a new radio button selector at the top to manually switch between the open-loop and closed-loop modes. Attempting to adjust the open-loop controls while in closed loop (or vice-versa) will still switch the mode to ensure interactivity, but hopefully the transition will be a bit more obvious.

**Comment by benjamin-antupit** [comment]
Looks great! Thanks for the quick update.
